#!/usr/bin/env python
#  -*- coding: utf-8 -*-
from __future__ import print_function, division

import nix
import matplotlib.pyplot as plt
import argparse

from plotting import Plotter

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='NIX Plotter')
    parser.add_argument('file', type=str)
    parser.add_argument('array', nargs='+')
    parser.add_argument('--block', type=str, default=None)
    parser.add_argument('-o, --output', dest='output', type=str, default=None)
    parser.add_argument('-H, --height', dest='height', type=float, default=13.7)
    parser.add_argument('-W, --width', dest='width', type=float, default=24.7)
    parser.add_argument('-U, --unit', dest='unit', type=str, default='cm')
    args = parser.parse_args()

    nf = nix.File.open(args.file, nix.FileMode.ReadOnly)
    block = nf.blocks[args.block or 0]

    plotter = Plotter()

    for da_id in args.array:
        da = block.data_arrays[da_id]
        plotter.add_plot(da)

    if args.output:
        plotter.save(args.output, width=args.width, height=args.height, units=args.unit)
    else:
        plt.show()